# Generated by Django 5.1.1 on 2024-11-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('prise', models.IntegerField()),
                ('img', models.ImageField(upload_to='banner/')),
            ],
        ),
        migrations.CreateModel(
            name='Camputers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('prise', models.IntegerField()),
                ('prise2', models.IntegerField()),
                ('img', models.ImageField(upload_to='camputers/')),
            ],
        ),
        migrations.CreateModel(
            name='Catagary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('prise', models.IntegerField()),
                ('prise2', models.IntegerField()),
                ('img', models.ImageField(upload_to='catagary/')),
            ],
        ),
        migrations.CreateModel(
            name='Mansclothers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('prise', models.IntegerField()),
                ('img', models.ImageField(upload_to='mansclother/')),
            ],
        ),
        migrations.CreateModel(
            name='Woman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='woman/')),
            ],
        ),
    ]
